''' Holds constants, mostly for server endpoints '''


# // main server URL //
BASE_URL = "http://127.0.0.1:3000/"

# // users route //
USERS_ROUTE = "users/"
GET_ALL_USERS_ROUTE = BASE_URL+USERS_ROUTE+"getAll"
CREATE_USERS_ROUTE = BASE_URL+USERS_ROUTE+"create"
AUTH_USER = BASE_URL+USERS_ROUTE+"auth"
GET_USER_RECORD = BASE_URL+USERS_ROUTE+"getUserRecord"
UPDATE_USER_PASSWORD = BASE_URL+USERS_ROUTE+"updatePassword"

# // league route //
LEAGUE_ROUTE = "league/"
GET_LEAGUE_ROUTE = BASE_URL+LEAGUE_ROUTE+"getLeague"
GET_ALL_LEAGUE_ROUTE = BASE_URL+LEAGUE_ROUTE+"getAllLeagues"
GET_ALL_AVAIL_LEAGUE_ROUTE = BASE_URL+LEAGUE_ROUTE+"getAvailableLeagues"
CREATE_LEAGUE_ROUTE = BASE_URL+LEAGUE_ROUTE+"createLeague"

# // league operations route //
LEAGUE_OPS_ROUTE = "leagueOps/"
GET_ALL_ROSTERS = BASE_URL + LEAGUE_OPS_ROUTE + "getAllRosters"
LEAGUE_OPS_ADD_USER = BASE_URL+LEAGUE_OPS_ROUTE+"addUsers"
LEAGUE_OPS_DEL_USER = BASE_URL+LEAGUE_OPS_ROUTE+"removeUser"
LEAGUE_OPS_WEEKLY_UPDATE = BASE_URL+LEAGUE_OPS_ROUTE+"weeklyUpdate"
LEAGUE_OPS_WEEKLY_POLL = BASE_URL+LEAGUE_OPS_ROUTE+"weeklyPoll"
LEAGUE_OPS_GET_ROSTERS_BY_LEAGUENAME= BASE_URL+LEAGUE_OPS_ROUTE+"getAllLeagueRosters"

# // token table //
TOKEN_ROUTE="tokens/"
GET_TOKEN=BASE_URL+TOKEN_ROUTE+"getToken"

# // notif center //
NOTIFICATION_CENTER="notifications/"
GET_ALL_NOTIFS=BASE_URL+NOTIFICATION_CENTER+"get"
GET_ALL_ACTIVE_NOTIFS=BASE_URL+NOTIFICATION_CENTER+"getAllActive"
CHANGE_NOTIF_STATUS=BASE_URL+NOTIFICATION_CENTER+"updateNotification"
MAKE_NEW_NOTIFICATION=BASE_URL+NOTIFICATION_CENTER+"newNotification"
